name: relationshipquestionsinc
favicon: null
layout_spectrum: 0.9835285807494074
typography_spectrum: 0.10884782951325178
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#aa744e'
    - '#53341f'
    - '#935e3e'
    - '#2e130c'
    - '#c29b7a'
  brandStrength: 0.12477784301154315
  lightness: 0.9729952646885067
  saturation: 0.5165583207271993
  rhythmicContrast: 0.2951803442556411
purpose: []
