name: relationshipquestionsinc
favicon: null
layout_spectrum: 0.31408
typography_spectrum: 0.91853
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3b9c9c'
    - '#ffffff'
    - '#333333'
    - '#73b8b8'
    - '#6b6f6f'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
